import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { DEFAULT_DATA, COMMON_SKILLS, SPECIALIZED_SKILLS, STAT_LABELS, INITIAL_SKILL_POINTS, MAX_SKILL_VALUE } from '../constants/game'
import { characterService } from '../lib/characters'
import { calculateHp, calculateMp, isInitialDataValid, remainingSkillPoints, remainingStatPoints, updateStat } from '../lib/characterRules'
import { useAuth } from '../hooks/useAuth'
import { Icon } from '../components/Icons'
import { StatusMessage } from '../components/StatusMessage'
import { NumericInput } from '../components/NumericInput'
import type { CharacterData, CharacterRecord, SpecializedSkillId, StatId } from '../types/character'

const freshData = (): CharacterData => structuredClone(DEFAULT_DATA) as CharacterData
const newId = () => crypto.randomUUID()

export function CharacterEditorPage() {
  const { id } = useParams(); const isNew = !id; const { user } = useAuth(); const navigate = useNavigate()
  const [character, setCharacter] = useState<CharacterRecord | null>(null); const [data, setData] = useState<CharacterData>(() => freshData()); const [name, setName] = useState(''); const [portraitFile, setPortraitFile] = useState<File | null>(null); const [loading, setLoading] = useState(!isNew); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false); const [error, setError] = useState(''); const [dirty, setDirty] = useState(false)

  useEffect(() => { if (isNew || !user || !id) return; void characterService.get(id, user.id).then((record) => { setCharacter(record); setName(record.name); setData({ ...record.data, statBonuses: { ...DEFAULT_DATA.statBonuses, ...record.data.statBonuses } }); }).catch((e) => setError(e instanceof Error ? e.message : 'キャラクターを読み込めませんでした')).finally(() => setLoading(false)) }, [id, isNew, user])
  useEffect(() => { const beforeUnload = (event: BeforeUnloadEvent) => { if (dirty && !saving) { event.preventDefault(); event.returnValue = '' } }; window.addEventListener('beforeunload', beforeUnload); return () => window.removeEventListener('beforeunload', beforeUnload) }, [dirty, saving])
  const statRemaining = remainingStatPoints(data.stats); const skillRemaining = remainingSkillPoints(data.skills)
  const canSave = name.trim().length > 0 && (!isNew || isInitialDataValid(data)) && !saving

  const update = (next: CharacterData) => { setData(next); setDirty(true); setSaved(false) }
  const save = async (event: React.FormEvent) => {
    event.preventDefault(); setError(''); setSaved(false); if (!canSave || !user) return; setSaving(true)
    try {
      if (isNew) {
        const created = await characterService.create(user.id, name.trim(), data)
        let portraitPath: string | null = null
        if (portraitFile) portraitPath = await characterService.uploadPortrait(user.id, created.id, portraitFile)
        if (portraitPath) await characterService.update(created.id, user.id, name.trim(), data, portraitPath)
        navigate(`/characters/${created.id}`, { replace: true })
      } else if (id) {
        const previousPortraitPath = character?.portrait_path ?? null
        let portraitPath = previousPortraitPath
        if (portraitFile) portraitPath = await characterService.uploadPortrait(user.id, id, portraitFile)
        await characterService.update(id, user.id, name.trim(), data, portraitPath)
        if (portraitFile && previousPortraitPath && previousPortraitPath !== portraitPath) await characterService.removePortrait(previousPortraitPath)
        setPortraitFile(null); setDirty(false); setSaved(true)
      }
    } catch (e) { setError(e instanceof Error ? e.message : '保存に失敗しました') }
    finally { setSaving(false) }
  }

  if (loading) return <div className="loading-state">キャラクターを読み込んでいます…</div>
  return <div className="page page-editor">
    <div className="editor-top"><Link to={isNew ? '/characters' : `/characters/${id}`} className="back-link"><Icon name="back" /> 一覧に戻る</Link><div className="save-state">{saving ? '保存中…' : saved ? <><Icon name="check" /> 保存しました</> : '変更を保存していません'}</div></div>
    <section className="editor-heading"><div><span className="eyebrow">{isNew ? 'NEW CHARACTER' : 'EDIT CHARACTER'}</span><h1>{isNew ? '新しいキャラクター' : 'キャラクターを編集'}</h1><p>{isNew ? '基本情報を入力して、あなたの物語を始めましょう。' : '現在のシートを更新します。'}</p></div><div className="resource-pills"><span>能力 <b>{Math.max(0, statRemaining)}</b> / 18</span><span>技能 <b>{Math.max(0, skillRemaining)}</b> / {INITIAL_SKILL_POINTS}</span></div></section>
    {error && <StatusMessage tone="error">{error}</StatusMessage>}
    <form onSubmit={save} className="editor-form">
      <section className="form-section portrait-section"><SectionTitle number="01" title="立ち絵" detail="キャラクターの印象を決める一枚。JPG / PNG / WebP、5MBまで。"/><PortraitEditor character={character} file={portraitFile} onChange={(file) => { if (file && file.size > 5 * 1024 * 1024) { setError('立ち絵は5MB以下の画像を選択してください。'); return } setError(''); setPortraitFile(file); setDirty(true) }} /></section>
      <section className="form-section"><SectionTitle number="01" title="基本情報"/><div className="basic-grid"><label className="field field-wide">名前 *<input required value={name} onChange={(e) => { setName(e.target.value); setDirty(true) }} placeholder="例：アリア・ノクス" /></label><label className="field">読み方<input value={data.profile.reading} onChange={(e) => update({ ...data, profile: { ...data.profile, reading: e.target.value } })} placeholder="例：ありあ・のくす" /></label><label className="field">年齢<input type="number" min="0" max="999" value={data.profile.age ?? ''} onChange={(e) => update({ ...data, profile: { ...data.profile, age: e.target.value === '' ? null : Math.max(0, Number(e.target.value)) } })} placeholder="—" /></label><label className="field">性別<input value={data.profile.gender} onChange={(e) => update({ ...data, profile: { ...data.profile, gender: e.target.value } })} placeholder="自由記述" /></label><label className="field">職業<input value={data.profile.occupation} onChange={(e) => update({ ...data, profile: { ...data.profile, occupation: e.target.value } })} placeholder="例：遺跡調査員" /></label><label className="field field-wide">一言説明<input value={data.profile.summary} onChange={(e) => update({ ...data, profile: { ...data.profile, summary: e.target.value } })} placeholder="このキャラクターを一言で表すと？" /></label><label className="field field-full">プロフィール<textarea rows={5} value={data.profile.description} onChange={(e) => update({ ...data, profile: { ...data.profile, description: e.target.value } })} placeholder="生い立ち、性格、目標など自由に記録できます。" /></label></div></section>
      <section className="form-section"><SectionTitle number="02" title="能力値" detail="初期値をポイントで配分し、追加値は成長・装備などの補正として入力できます。"/><div className="stat-layout"><div className="stat-list">{(Object.keys(STAT_LABELS) as StatId[]).map((statId) => <StatRow key={statId} id={statId} value={data.stats[statId]} bonus={data.statBonuses?.[statId] ?? 0} onChange={(delta) => update({ ...data, stats: updateStat(data.stats, statId, delta, isNew) })} onBonusChange={(bonus) => update({ ...data, statBonuses: { ...data.statBonuses, [statId]: bonus } })} />)}</div><div className="derived-card"><span className="eyebrow">DERIVED VALUES</span><div className="derived-row"><span>HP <small>体力合計 × 3</small></span><strong>{calculateHp(data.stats, data.statBonuses)}</strong></div><div className="derived-row"><span>MP <small>精神力合計 × 3</small></span><strong>{calculateMp(data.stats, data.statBonuses)}</strong></div><div className={`points-left ${statRemaining === 0 ? 'points-done' : ''}`}><span>残り能力ポイント</span><b>{Math.max(0, statRemaining)} <small>/ 18</small></b></div></div></div></section>
      <section className="form-section"><SectionTitle number="03" title="技能" detail="通常・武器・射撃・専門知識・カスタムを同じ表で管理します。追加技能は表の行として増えます。"/><div className="skill-total"><span>残り技能ポイント</span><b className={skillRemaining < 0 ? 'negative' : ''}>{skillRemaining} <small>/ {INITIAL_SKILL_POINTS}</small></b></div><SkillTable data={data} update={update} /></section>
      <section className="form-section"><SectionTitle number="04" title="持ち物" detail="冒険に持っていくものを記録します。"/><ItemsEditor data={data} update={update} /></section>
      <section className="form-section compact-section"><SectionTitle number="05" title="通過シナリオ" detail="シナリオ名と、そのキャラクターに起きた出来事や得た経験を記録します。"/><div className="experience-grid"><label className="field field-full"><span>通過シナリオ</span><textarea rows={8} value={data.experience.notes ?? ''} onChange={(e) => update({ ...data, experience: { ...data.experience, notes: e.target.value } })} placeholder="例：\n・廃都の地下 — 仲間と再会し、古代文字を読めるようになった。\n・月影の港 — 船長との約束を果たした。" /></label></div></section>
      <section className="form-section"><SectionTitle number="06" title="タグ" detail="検索や分類に使うタグを追加します。"/><TagsEditor data={data} update={update} /></section>
      <div className="form-actions"><Link to={isNew ? '/characters' : `/characters/${id}`} className="button button-ghost">キャンセル</Link><button className="button button-dark" disabled={!canSave}>{saving ? '保存中…' : 'キャラクターを保存する'} <Icon name="arrow" /></button></div>
      {isNew && !isInitialDataValid(data) && <p className="form-hint">能力ポイントをすべて割り振ると保存できます。</p>}
    </form>
  </div>
}

function SectionTitle({ number, title, detail }: { number: string; title: string; detail?: string }) { return <div className="section-title"><span className="section-number">{number}</span><div><h2>{title}</h2>{detail && <p>{detail}</p>}</div></div> }
function StatRow({ id, value, bonus, onChange, onBonusChange }: { id: StatId; value: number; bonus: number; onChange: (delta: number) => void; onBonusChange: (value: number) => void }) { return <div className="stat-row"><span className="stat-label">{STAT_LABELS[id]}</span><div className="stat-cell"><small>初期値</small><div className="stat-stepper"><button type="button" className="stepper-button" onClick={() => onChange(-1)} disabled={value <= 1}><Icon name="minus" /></button><output>{value}</output><button type="button" className="stepper-button" onClick={() => onChange(1)}><Icon name="plus" /></button></div></div><div className="stat-cell stat-bonus-cell"><small>追加値</small><NumericInput aria-label={`${STAT_LABELS[id]}追加値`} min={0} max={100} value={bonus} onChange={onBonusChange} /></div><div className="stat-cell stat-total-cell"><small>合計</small><output>{value + bonus}</output></div></div> }

type SkillTableRow = { key: string; category: string; label: string; note: string; value: number; editableLabel: boolean; onLabelChange?: (value: string) => void; onValueChange: (value: number) => void; onDelete?: () => void }

function SkillTable({ data, update }: { data: CharacterData; update: (next: CharacterData) => void }) {
  const rows: SkillTableRow[] = [
    ...COMMON_SKILLS.map((skill) => ({ key: skill.id, category: '通常', label: skill.label, note: skill.note, value: data.skills.common[skill.id], editableLabel: false, onValueChange: (value: number) => updateSkill(data, update, value, data.skills.common[skill.id], (nextSkillValue) => ({ ...data, skills: { ...data.skills, common: { ...data.skills.common, [skill.id]: nextSkillValue } } })) })),
    ...SPECIALIZED_SKILLS.flatMap((group) => data.skills[group.id].map((skill) => ({ key: skill.id, category: group.label, label: skill.specialty, note: group.note, value: skill.value, editableLabel: true, onLabelChange: (label: string) => update({ ...data, skills: { ...data.skills, [group.id]: data.skills[group.id].map((item) => item.id === skill.id ? { ...item, specialty: label } : item) } }), onValueChange: (value: number) => updateSkill(data, update, value, skill.value, (nextSkillValue) => ({ ...data, skills: { ...data.skills, [group.id]: data.skills[group.id].map((item) => item.id === skill.id ? { ...item, value: nextSkillValue } : item) } })), onDelete: () => update({ ...data, skills: { ...data.skills, [group.id]: data.skills[group.id].filter((item) => item.id !== skill.id) } }) }))),
    ...data.skills.custom.map((skill) => ({ key: skill.id, category: 'カスタム', label: skill.name, note: '標準技能にない自由記述', value: skill.value, editableLabel: true, onLabelChange: (label: string) => update({ ...data, skills: { ...data.skills, custom: data.skills.custom.map((item) => item.id === skill.id ? { ...item, name: label } : item) } }), onValueChange: (value: number) => updateSkill(data, update, value, skill.value, (nextSkillValue) => ({ ...data, skills: { ...data.skills, custom: data.skills.custom.map((item) => item.id === skill.id ? { ...item, value: nextSkillValue } : item) } })), onDelete: () => update({ ...data, skills: { ...data.skills, custom: data.skills.custom.filter((item) => item.id !== skill.id) } }) })),
  ]
  const addSpecialized = (id: SpecializedSkillId) => update({ ...data, skills: { ...data.skills, [id]: [...data.skills[id], { id: newId(), specialty: '', value: 0 }] } })
  const addCustom = () => update({ ...data, skills: { ...data.skills, custom: [...data.skills.custom, { id: newId(), name: '', value: 0 }] } })
  return <div className="skill-table-panel"><div className="skill-table-wrap"><table className="skill-table"><thead><tr><th>区分</th><th>技能名</th><th>内容</th><th>技能値</th><th aria-label="操作" /></tr></thead><tbody>{rows.map((row) => <tr key={row.key}><td><span className="skill-category-chip">{row.category}</span></td><td>{row.editableLabel ? <input aria-label={`${row.category}技能名`} value={row.label} onChange={(event) => row.onLabelChange?.(event.target.value)} placeholder="技能名" /> : <b className="skill-name">{row.label}</b>}</td><td className="skill-note">{row.note}</td><td><div className="skill-value-input"><NumericInput aria-label={`${row.label || row.category}技能値`} min={0} max={MAX_SKILL_VALUE} value={row.value} onChange={row.onValueChange} /><span>/ 100</span></div></td><td>{row.onDelete && <button type="button" className="text-button danger" onClick={row.onDelete}><Icon name="trash" />削除</button>}</td></tr>)}</tbody></table></div><div className="skill-add-actions">{SPECIALIZED_SKILLS.map((group) => <button type="button" className="add-link" key={group.id} onClick={() => addSpecialized(group.id)}><Icon name="plus" />{group.label}を追加</button>)}<button type="button" className="add-link" onClick={addCustom}><Icon name="plus" />カスタム技能を追加</button></div></div>
}

function updateSkill(data: CharacterData, update: (next: CharacterData) => void, value: number, current: number, build: (nextValue: number) => CharacterData) { const nextValue = Math.max(0, Math.min(MAX_SKILL_VALUE, Math.round(Number.isFinite(value) ? value : 0))); if (nextValue > current && remainingSkillPoints(data.skills) < nextValue - current) return; update(build(nextValue)) }

function ItemsEditor({ data, update }: { data: CharacterData; update: (next: CharacterData) => void }) { const add = () => update({ ...data, items: [...data.items, { id: newId(), name: '', quantity: 1, description: '' }] }); return <div className="items-editor">{data.items.length === 0 && <p className="muted-copy">まだ持ち物がありません。</p>}{data.items.map((item) => <div className="item-row" key={item.id}><input aria-label="持ち物名" value={item.name} onChange={(e) => update({ ...data, items: data.items.map((i) => i.id === item.id ? { ...i, name: e.target.value } : i) })} placeholder="アイテム名" /><input aria-label="個数" type="number" min="1" value={item.quantity} onChange={(e) => update({ ...data, items: data.items.map((i) => i.id === item.id ? { ...i, quantity: Math.max(1, Number(e.target.value)) } : i) })} /><input aria-label="持ち物の説明" value={item.description} onChange={(e) => update({ ...data, items: data.items.map((i) => i.id === item.id ? { ...i, description: e.target.value } : i) })} placeholder="説明" /><button type="button" className="icon-button danger-icon" onClick={() => update({ ...data, items: data.items.filter((i) => i.id !== item.id) })}><Icon name="trash" /></button></div>)}<button type="button" className="add-link" onClick={add}><Icon name="plus" /> 持ち物を追加</button></div> }
function TagsEditor({ data, update }: { data: CharacterData; update: (next: CharacterData) => void }) { const [value, setValue] = useState(''); const add = () => { const tag = value.trim(); if (!tag || data.tags.includes(tag)) return; update({ ...data, tags: [...data.tags, tag] }); setValue('') }; return <div className="tags-editor"><div className="tag-input"><input value={value} onChange={(e) => setValue(e.target.value)} onKeyDown={(e) => { if (e.key === 'Enter') { e.preventDefault(); add() } }} placeholder="タグを入力してEnter" /><button type="button" className="button button-outline" onClick={add}>追加</button></div><div className="tag-row large-tags">{data.tags.map((tag) => <button type="button" className="tag removable-tag" key={tag} onClick={() => update({ ...data, tags: data.tags.filter((item) => item !== tag) })}>{tag} ×</button>)}</div></div> }
function PortraitEditor({ character, file, onChange }: { character: CharacterRecord | null; file: File | null; onChange: (file: File | null) => void }) { const preview = file ? URL.createObjectURL(file) : character?.portrait_url; return <div className="portrait-editor"><div className="portrait-preview">{preview ? <img src={preview} alt="立ち絵プレビュー" /> : <span>✦</span>}</div><div><label className="upload-button"><Icon name="upload" /> {file ? '画像を変更' : '画像を選択'}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={(e) => onChange(e.target.files?.[0] ?? null)} /></label>{file && <button type="button" className="text-button danger" onClick={() => onChange(null)}>選択を取り消す</button>}<p className="upload-help">推奨：正方形または縦長 / 5MB以下</p></div></div> }
